workflows:
  android-debug:
    name: MacroSnap Debug APK
    max_build_duration: 30
    working_directory: "Files/Source repo"
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - "Files/Source repo/build/app/outputs/**/*.apk"